### ISSUE TITLE
1주차 진행

### ISSUE THREAD

**Issue by juunini** [CodeSoom/project-react-2-juunini#1]
1. 이 앱을 언제 사용하나요?
    - 해외 브랜드를 직구할 때 관세, 부가세, 배송비 등을 따로 계산해야 하는 경우엔 머리가 아픈데
    그런 고민 없이 견적을 얻고싶을 때 이용합니다.
    제 취향인 브랜드 [killstar](https://www.killstar.com/), [disturbia](https://www.disturbia.co.uk/), [rogue & wolf](https://rogueandwolf.com/) 등을 다룰 예정입니다.
2. 제약 조건은 무엇인가요?
    - 구매는 구현하지 않고, 해당 브랜드의 페이지로 갈 수 있는의 링크를 제공합니다.
    오로지 아이템 리스트를 제공하고
    환율, 관세, 부가세, 배송비의 계산만 제공합니다.
3. 구체적인 사례는 무엇인가요?
    - https://fetching.co.kr/
    현재 근무중인 회사의 사이트인데, 여기 외에도 이런식의 서비스를 제공하는 다른 곳도 많습니다.
4. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.

    ### 프로젝트 환경 세팅
    - [x] eslint 세팅
    - [x] typescript 환경 세팅
    - [x] github ci 부착

    ### 상품 리스트 페이지 구현
    - [x] 샘플 데이터 준비 (브랜드 정보)
    - [x] 샘플 데이터 준비 (상품 리스트)
    - [x] CSS 없이 일단 리스트를 보여줄 수 있도록 하기
    이미지, 브랜드, 이름, 가격, 사이즈

    ### 배포
    - [x] Netlify 이용해보기

    ### 덤
    - [x] equal-dark.com 도매인 구매

**Comment by hannut91** [comment]
오 ㅎㅎㅎ 옷들이 멋지네요 ㅎㅎ

해외 브랜드 옷들을 구매하기전에 구매하는데 드는 전체적인 비용을 미리 예상해주고 알려주는 서비스인가요? 시나리오가 아직 잘 떠오르지 않는 것 같아요 ㅠ

예를들어서 내가 어떤 사이트를 돌아보다가 맘에드는 옷을 찾았어요. 이 옷을 구매할 때 드는 관세, 부가세, 배송비들을 같이 계산해서 예상되는 가격을 보여주는 애플리케이션인가요?

**Comment by juunini** [comment]
1. 애플리케이션에서 취급할 브랜드의 정보를 수집할거에요. (국가, 관세, 부가세, 배송비, 환율 등)
2. 그 브랜드의 상품들을 수집할거에요. (브랜드, 이름, 원본 링크, 가격, 설명, 사이즈, 품절여부)
3. 애플리케이션을 이용하면 마치 샵 처럼 상품들을 진열해서 보여주고, 클릭하면 상세정보도 볼 수 있어요.
4. 상품 진열 페이지에는 (환율이 적용된 한국 돈 + 관세 + 부가세) 를 표시해주고
  상세페이지에 오면 일반적인 샵 처럼 상품의 설명과 사이즈 표 등 기본적인걸 표시해주고
  가격 표시를 하는 부분에는 원래 판매하는 외화의 가격, 환율 적용된 한국 돈, 관세, 부가세, 배송비를 표시해서 보여줄거에요.
5. 카트에 담으면 브랜드별로 따로 합산해 배송비 여부를 판별해줄거에요.
6. 판매는 제공하지 않을거에요. 일을 해보니 너무 힘든걸 알아서... ㅎㅎ; 오로지 정보 제공만 하려구요! 포트폴리오니까요.
7. 애플리케이션이 완성되면 샘플데이터가 아닌 백엔드를 만들어서 진짜 데이터를 지속적으로 수집해서 제공 할 생각이에요!
8. 조금 더 욕심내면 최근 리액트 네이티브 사용법을 익힌 겸 앱도 제작해보고 싶어요.

**Comment by wholemann** [comment]
오 좋군요... typescript를 쓰면 좋은 도메인 같네요ㅎㅎ

이번주에 당장 서비스 시작하려면 계산 기능도 나중으로 미루고, 말씀하신대로 정보만 잘 모아서 보여줘도

충분히 가치가 제공될 거 같습니다. 방향 잘 잡으신 것 같아요.

**Comment by hannut91** [comment]
현재 진행사항이 궁금해요 ㅎㅎ

**Comment by juunini** [comment]
샘플데이터를 수집하고 있습니다.
사실 어제는 시간을 거의 못써서 별로 못했다고 하는게 맞겠군요 ㅠㅠ
