### ISSUE TITLE
크롤러 개발 / fixtures 갱신

### ISSUE THREAD

**Issue by juunini** [CodeSoom/project-react-2-juunini#35]
# 목적
크롤러를 개발해서 front-end 코드에 넣어둔 fixtures 를 갱신한다.
크롤러를 자동으로 실행이 가능하도록 하기 전에 먼저 수동 작동이 가능하도록 만들어 보려는 계획.

# 목표 일정
- 크롤러 개발 : 2021-01-31 까지
- fixtures 갱신 : 2021-02-02 까지

**Comment by ahastudio** [comment]
업그레이드 예정은 없는 건가요 👀

**Comment by juunini** [comment]
@ahastudio 네 일단은 지금 하는 vr 개발이 재밌다보니 당장 여기로 눈이 안가긴 하네요
