### ISSUE TITLE
README를 꾸며주세요

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-juunini#6]
사람들이 어떤 앱인지 알 수 있도록 간단한 소개를 해주세요

현재 결과물은 사용자가 어떻게 사용할 수 있는지도 같이 작성해주세요

**Comment by juunini** [comment]
간단한 소개와 함께

- 현재까지 진행 된 부분
- 이번주에 진행 할 부분
- 다음주에 진행 계획중인 부분

이렇게 작성해보았습니다.
